[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
chalna = "fSLsjTm9PGfbrAgosY2kYb1MnFEpn8LALo5cY5a4AkJ"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
